version: '2'

services:
  ll-es:
    container_name: ll-es
    build:
      dockerfile: elasticsearch.Dockerfile
      context: ./elasticsearch
    ports: 
      - "80:9200"
      - "9300:9300"
    environment:
      discovery.type: single-node
  indexer:
    image: python:3.7
    container_name: indexer
    volumes:
      - ./indexer:/indexer
    working_dir: /indexer
    command: pip install -r requirements.txt 
    depends_on:
      - ll-es
    links:
      - ll-es