version: '3.3'

services:
  ll-es:
    container_name: ll-es
    image: "282251075226.dkr.ecr.eu-west-1.amazonaws.com/linklives-elasticsearch:${IMAGE_TAG}"
    ports: 
      - "80:9200"
    environment:
      - "discovery.type=single-node"
    env_file:
      - .env
    volumes:
      - "/elasticsearch-data:/usr/share/elasticsearch/data"
    
    

    