version: '3.3'

services:
  ll-es:
    container_name: ll-es
    image: "282251075226.dkr.ecr.eu-west-1.amazonaws.com/linklives-elasticsearch:{image-tag}"
    ports: 
      - "80:9200"
    environment:
      - "discovery.type=single-node"
    env_file:
      - .env
    volumes:
      - "/elasticsearch-data:/usr/share/elasticsearch/data"
  bash:
    container_name: restorer
    image: dwdraju/alpine-curl-jq:latest
    entrypoint: sh /restore-snapshot.sh
    volumes:
      - ./restore-snapshot.sh:/restore-snapshot.sh