version: '3.3'

services:
  ll-es:
    container_name: ll-es
    build:
      dockerfile: elasticsearch.Dockerfile
      context: ./elasticsearch
    ports: 
      - "90:9200"
      - "9300:9300"
    environment:
      discovery.type: single-node
  bash:
    container_name: restorer
    image: curlimages/curl:latest
    entrypoint: sh /restore-snapshot.sh
    volumes:
      - ./restore-snapshot.sh:/restore-snapshot.sh