branch-defaults:
  master:
    environment: link-lives-data
environment-defaults:
  link-lives-data-prod:
    branch: null
    repository: null
global:
  application_name: link-lives-data
  default_ec2_keyname: null
  default_platform: Multi-container Docker running on 64bit Amazon Linux
  default_region: eu-west-1
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: null
  sc: git
  workspace_type: Application
